### ISSUE TITLE
Support Python 3.6 on macOS

### ISSUE THREAD

**Issue by nikolay** [Gigoteur/PX8#19]
```
$ ./px8
dyld: Library not loaded: libpython3.5m.dylib
  Referenced from: /Users/username/Downloads/PX8-0.0.1-OSX/./px8
  Reason: image not found
Abort trap: 6
```

**Comment by hallucino** [comment]
Hi,

thank you for the report.

I noticed this bug too and right now you could install python 3 on OSX and export the following env variable DYLD_FALLBACK_LIBRARY_PATH, e.g:
export DYLD_FALLBACK_LIBRARY_PATH=/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib

I will try to understand how to do it automatically

**Comment by hallucino** [comment]
Does it work ?

**Comment by hallucino** [comment]
?

**Comment by nikolay** [comment]
@hallucino Yeah, this made it pass beyond the initial crash, but it still doesn't work (due to Rust issues now).

**Comment by hallucino** [comment]
what is the output ?

**Comment by nikolay** [comment]
@hallucino For sure, it does not work in the itch.io desktop client. When I go to `~/Library/Application Support/itch/apps/PX8/PX8` and run it, then some games (with `.px8` file) work, others (like flappy) and fill up the console with:
```
[2017-04-29][14:36:32][WARN] DRAW = PyErr { ptype: <class 'OverflowError'>, pvalue: None, ptraceback: Some(<traceback object at 0x117962c48>) }
```
Is it possibly to somehow remove the annoying FPS header?

Anyway, it looks like only flappy does not work at this time with the latest release.

**Comment by hallucino** [comment]
ok so it seems ok, Flappy was more a test so I will take a look

**Comment by hallucino** [comment]
@nikolay for the FPS, use F2 to disable it
