### ISSUE TITLE
error: proc-macro derive panicked

### ISSUE THREAD

**Issue by iezed** [Gigoteur/PX8#29]
Hello, I compiled with this command : 
PX8_SCREEN_WIDTH=256 PX8_SCREEN_HEIGHT=256 cargo build --features="lua" --release
and I have this error. I have rust 1.17 on osx 10.10.5. 
Thanks.
error: proc-macro derive panicked
   --> src/cartridge/mod.rs:905:21
    |
905 | #[derive(Serialize, Deserialize)]
    |                     ^^^^^^^^^^^
    |
    = help: message: proc_macro::__internal::with_parse_sess() called before set_parse_sess()!

error: Could not compile `px8`.

**Comment by hallucino** [comment]
Weird !

Could you done a cargo clean to be sure ?

**Comment by iezed** [comment]
I done a cargo clean, but nothing change.

**Comment by hallucino** [comment]
I can't reproduce this bug, it is weird

**Comment by hallucino** [comment]
It seems related to Serde, @dtolnay: have you an idea ?

**Comment by dtolnay** [comment]
This is rust-lang/rust#39870. The homebrew packaging for Rust is hosed. Uninstall everything Rust-related with homebrew and reinstall with https://rustup.rs/ to fix this.

**Comment by hallucino** [comment]
@dtolnay: Thanks !

@iezed tell me if it works to close the bug !

**Comment by iezed** [comment]
Thanks, I'll try in this day.

**Comment by iezed** [comment]
I reinstall rust with rustup, and now can build. Thanks.

**Comment by ilovezfs** [comment]
This should no longer be a problem in Homebrew due to https://github.com/Homebrew/homebrew-core/pull/14490.

**Comment by hallucino** [comment]
thx !
