### ISSUE TITLE
Add more python/lua/rust examples

### ISSUE THREAD

**Issue by iezed** [Gigoteur/PX8#31]
Hi, I do not see examples in rust or lua, could you write some examples? Thank you.

**Comment by hallucino** [comment]
Yes sure, it is a good idea !

**Comment by hallucino** [comment]
I started to add some examples:

- lua -> https://github.com/Gigoteur/PX8/tree/master/examples/helloworld/lua
- rust -> https://github.com/Gigoteur/PX8/blob/master/examples/helloworld.rs

**Comment by hallucino** [comment]
- [ ] Python examples
- [ ] Lua examples
- [ ] Rust examples
- [ ] PX8 [Tutorial](https://github.com/Gigoteur/PX8/wiki)

**Comment by iezed** [comment]
thank you, very grateful.
