### ISSUE TITLE
Fix display depth to maximum of 8bpp?

### ISSUE THREAD

**Issue by johnbatty** [Gigoteur/PX8#43]
The current code supports an 8bpp (and 4bpp, if you only use the first 16 colour values!), with a color translation on drawing (palt()), and a mapping to RGB on display (via a configurable 256 entry palette).  This fits with retro games consoles capabilities, and given the default low resolution and retro palettes provided this seems to be the main target for PX8.

However, internally the code currently stores pixels as 32bpp, and some functions seem to be written to support either color indexes or RGB values.

Do you have any strong desire to support more than 8bpp (i.e. 24bpp) in PX8?
I think that if you took the decision to only support up to 8bpp (at least for now) then the code could be simplified and I know could have some good performance improvements (I've already made them!).  As PICO-8 demonstrates, sometimes limitations are a good thing :-)

**Comment by hallucino** [comment]
Yes sure !

I was doing some experiments with the 32bpp, so feel free to delete it, specially if there is an improvement ! Could you keep the palette switching ?

**Comment by johnbatty** [comment]
Ok great.  I'll submit a pull request.  It has still got palette switching (which uses an array rather than a HashMap).  I think you'll be pleased with the performance improvement :-)

**Comment by hallucino** [comment]
got it !
