### ISSUE TITLE
Add trollmini font

### ISSUE THREAD

**Issue by hallucino** [Gigoteur/PX8#52]
See:
https://www.patreon.com/posts/12232698

@johnbatty do you think it is possible ?

**Comment by hallucino** [comment]
@johnbatty ? :)

**Comment by hallucino** [comment]
@johnbatty are you still here ?

**Comment by johnbatty** [comment]
Hi.  I'm still alive! Just incredibly busy at the moment, so no time to work on PX8 :-(
Hopefully I'll be able to get back to it soon.
Yep, definitely possible to add new fonts - it just needs the work to create the definition...

**Comment by Matt-McConway** [comment]
I've almost got this finished.
Let me know if you want me to submit a pull request when it's done :)

Loving this project!

**Comment by hallucino** [comment]
@Matt-McConway yes please you're welcome !

**Comment by Matt-McConway** [comment]
@hallucino I've created the pull request now. Let me know if I've done anything wrong! This is my first time working with Rust and my first time collaborating on github, so hopefully I got it right :)

**Comment by hallucino** [comment]
Thank you !

**Comment by hallucino** [comment]
@Matt-McConway do you want to add more fonts ?

**Comment by Matt-McConway** [comment]
Sure! What did you have in mind?

**Comment by hallucino** [comment]
We could find more tiny fonts, but we could also have the ability to zoom in a font

**Comment by Matt-McConway** [comment]
Alright, I'll take a look!

What do you mean by zooming in a font?

**Comment by hallucino** [comment]
We could change the size of the font, to have different view of it

**Comment by Matt-McConway** [comment]
Similar to how you change the size of a font in text editors (e.g. 10pt, 12pt etc)? Might be a bit beyond me, but I'll look into it :)
