### ISSUE TITLE
Lua

### ISSUE THREAD

**Issue by iezed** [Gigoteur/PX8#57]
Hi, on Ubuntu I try to build with lua plugin, but I have this error: 
'does not have these features: lua'. I need to install something? Thanks.

**Comment by Matt-McConway** [comment]
Just double checking, do you have Lua [installed](https://www.lua.org/download.html)?

**Comment by iezed** [comment]
Yes,I have lua 5.2.4.

**Comment by Matt-McConway** [comment]
I'm thinking only 5.3 and beyond is supported, based off what I found [here](https://github.com/Gigoteur/PX8/blob/master/src/plugins/lua/README.md).  @hallucino Do you know what's going on here?

**Comment by iezed** [comment]
I have, lua5.1, lua5.2, lua5.3 and liblua5.3-dev.

**Comment by hallucino** [comment]
Have you sync with the latest commit ? I did some modification yesterday. Do a 'cargo clean' before

**Comment by hallucino** [comment]
Oops sorry. Please use 'px8_plugin_lua' for the features option. I did that because I want to modify in depth the plugin yo speed up the perf.

**Comment by iezed** [comment]
Thanks.

**Comment by hallucino** [comment]
I added the modif here:
https://github.com/Gigoteur/PX8/blob/master/README.md#build
