### ISSUE TITLE
SdlError

### ISSUE THREAD

**Issue by matheynen** [Gigoteur/PX8#58]
Hi, I'm trying to use PX8 on UbuntuStudio 17.04.
I've got problem with libpython3.4m.so.1.0 but with this script it's ok [https://gist.github.com/puentesarrin/8290754](url)
Now I've got this error : `[2017-07-15][17:51:58][INFO] [SDL] Creating renderer
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SdlError("Couldn\'t find matching render driver")', /checkout/src/libcore/result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.
`
Thanks for help I would like to use this wonderful tool

**Comment by hallucino** [comment]
Waht is the command line you use to build the project ?

**Comment by hallucino** [comment]
@matheynen have you the command line please ?

**Comment by matheynen** [comment]
`cargo build --features="cpython px8_plugin_lua" --release`
I tried also with the binaries but same bug

**Comment by hallucino** [comment]
What is you graphical card ?

**Comment by matheynen** [comment]
Intel Corporation HD Graphics 5500. It's maybe a driver problem. I'm searching a solution

**Comment by matheynen** [comment]
Intel HD 5500. I've bug with ubuntu 17.04. I will downgrade

**Comment by matheynen** [comment]
Same bug on ubuntu 16.04

**Comment by hallucino** [comment]
Could you test some examples from:
https://github.com/AngryLawyer/rust-sdl2/tree/master/examples

to see if it works please ?

**Comment by matheynen** [comment]
Sound, mouse examples works but all graphic not, except 'no-renderer' and 'renderer-target'

**Comment by hallucino** [comment]
ok so it seems more a bug with SDL rather than PX8

**Comment by hallucino** [comment]
I will close this bug. It the example with rust-sdl2 works but not with PX8, please reopen this bug.

Thank you
